name: Main workflow

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 30
    strategy:
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 5
          - 4 # latest OCaml 4 release
          - 4.11.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@e32b06a3e831ff2fbc6f08cf35be2085e3918014 # v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true

      - name: Install system dependencies
        run: opam install conf-protoc --yes

      - name: Install opam dependencies
        run: opam install . --deps-only --with-doc --with-test --yes

      - name: Build
        run: opam exec -- dune build

      - name: Run tests
        run: opam exec -- dune runtest
